const curryUnaryFunction = (a) => (b) => (c) => a + b + c;

console.log(curryUnaryFunction(1));       // Returns: function (b) => ...
console.log(curryUnaryFunction(1)(2));    // Returns: function (c) => ...
console.log(curryUnaryFunction(1)(2)(3)); // Output: 6
